import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/shared/Navbar";
import Footer from "@/Components/shared/Footer";
import AuthProvider from "@/services/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Car Doctor Pro",
    template: "%s || Car Doctor Pro",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="w-10/12 mx-auto">
            <Navbar></Navbar>
          </div>
          <div>{children}</div>
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
